### ISSUE TITLE
Error with latest version of tModLoader Alpha

### ISSUE THREAD

**Issue by Explodiatr** [Cyrillya/Autofish#3]
Mod cannot be successfully enabled with the most recent alpha version of tModLoader.

Screenshot:

![image](https://user-images.githubusercontent.com/96837357/147685741-ccc39252-bc23-4ded-9dc2-84e8114aee91.png)

Logs:
```
[11:50:04] [Main Thread/INFO] [tML]: Enabling Mod: Autofish
[11:50:06] [.NET ThreadPool Worker/INFO] [tML]: Unloading mods
[11:50:06] [.NET ThreadPool Worker/INFO] [tML]: Unloading: tModLoader
[11:50:06] [.NET ThreadPool Worker/INFO] [tML]: Finding Mods...
[11:50:06] [.NET ThreadPool Worker/INFO] [tML]: Sandboxing: Autofish
[11:50:06] [.NET ThreadPool Worker/INFO] [tML]: Instantiating Mods...
[11:50:07] [.NET ThreadPool Worker/INFO] [tML]: Initializing: ModLoader v0.12
[11:50:07] [.NET ThreadPool Worker/INFO] [tML]: Initializing: Autofish v0.2.3
[11:50:07] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Projectile::FishingCheck() modified by Autofish
[11:50:07] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at MonoMod.Cil.ILCursor.GotoNext(MoveType moveType, Func`2[] predicates)
   at Autofish.AutofishPlayer.Projectile_FishingCheck(ILContext il) in AutofishPlayer.cs:line 107
   at MonoMod.Cil.ILContext.Invoke(Manipulator manip)
   at MonoMod.RuntimeDetour.ILHook.Context.InvokeManipulator(MethodDefinition def, Manipulator cb)
   at MonoMod.RuntimeDetour.ILHook.Context.Refresh()
   at MonoMod.RuntimeDetour.ILHook.Apply()
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator, ILHookConfig& config)
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator, ILHookConfig config)
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._NewILHook(MethodBase from, Manipulator to)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._Add[TDelegate](Func`3 gen, TDelegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint.Modify(Delegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify(MethodBase method, Delegate callback)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify[T](MethodBase method, Delegate callback)
   at IL.Terraria.Projectile.add_FishingCheck(Manipulator )
   at Autofish.AutofishPlayer.Load() in AutofishPlayer.cs:line 91
   at Terraria.ModLoader.ModType.Terraria.ModLoader.ILoadable.Load(Mod mod) in tModLoader\Terraria\ModLoader\ModType.cs:line 25
   at Terraria.ModLoader.Mod.AddContent(ILoadable instance) in tModLoader\Terraria\ModLoader\Mod.cs:line 140
   at Terraria.ModLoader.Mod.Autoload() in tModLoader\Terraria\ModLoader\Mod.Internals.cs:line 48
   at Terraria.ModLoader.ModContent.<>c.<Load>b__41_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 302
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 358
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 297
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 134
   at Terraria.ModLoader.ModLoader.<>c__DisplayClass45_0.<BeginLoad>b__0() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 114
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

[11:50:07] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading Autofish
The mod(s) have been automatically disabled.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at MonoMod.Cil.ILCursor.GotoNext(MoveType moveType, Func`2[] predicates)
   at Autofish.AutofishPlayer.Projectile_FishingCheck(ILContext il) in AutofishPlayer.cs:line 107
   at MonoMod.Cil.ILContext.Invoke(Manipulator manip)
   at MonoMod.RuntimeDetour.ILHook.Context.InvokeManipulator(MethodDefinition def, Manipulator cb)
   at MonoMod.RuntimeDetour.ILHook.Context.Refresh()
   at MonoMod.RuntimeDetour.ILHook.Apply()
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator, ILHookConfig& config)
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator, ILHookConfig config)
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._NewILHook(MethodBase from, Manipulator to)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._Add[TDelegate](Func`3 gen, TDelegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint.Modify(Delegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify(MethodBase method, Delegate callback)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify[T](MethodBase method, Delegate callback)
   at IL.Terraria.Projectile.add_FishingCheck(Manipulator )
   at Autofish.AutofishPlayer.Load() in AutofishPlayer.cs:line 91
   at Terraria.ModLoader.ModType.Terraria.ModLoader.ILoadable.Load(Mod mod) in tModLoader\Terraria\ModLoader\ModType.cs:line 26
   at Terraria.ModLoader.Mod.AddContent(ILoadable instance) in tModLoader\Terraria\ModLoader\Mod.cs:line 137
   at Terraria.ModLoader.Mod.Autoload() in tModLoader\Terraria\ModLoader\Mod.Internals.cs:line 48
   at Terraria.ModLoader.ModContent.<>c.<Load>b__41_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 302
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 358
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 297
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 134
[11:50:07] [.NET ThreadPool Worker/INFO] [tML]: Disabling Mod: Autofish
```

On an unrelated note, I also noticed that (while using the mod before the most recent tModLoader update) Wandering Eye Fish can spawn from fishing during a Blood Moon, even if the "Only catch non-enemies" option is enabled. Unsure if this is correct behavior.

Let me know if there's any additional information I can provide.

**Comment by Cyrillya** [comment]
Fixed with the newest update.
